### ISSUE TITLE
AVASS42,155-Raise alarm without internet connectivity

### ISSUE THREAD

**Issue by arunimanandy** [Scjatto/UCHSClient#1]
Raise alarm timeout not occurring

Steps to recreate:
1. Ensure device has no internet connectivity
2. Click on application icon
3. Click Raise alarm
4. Click Click on any one of the emergency buttons
5. Raise alarm action commences
6. Raise alarm action continues without timeout

**Comment by Scjatto** [comment]
Fixed timeout inactivity for raise alarm in the method sendAlarmToServer() under RaiseAlarmActivity

**Comment by arunimanandy** [comment]
issue fixed in release 0.2

**Comment by abhirup-dev** [comment]
@arunimanandy please don't write AVASS in the issue title. It's AVAAS. 😑

**Comment by arunimanandy** [comment]
@maverickdas 
![test case title](https://user-images.githubusercontent.com/49411568/83329406-eba5bd80-a2a6-11ea-8261-5fccb3b9ebc9.JPG)

This is the official test case id from test link. It is put here for traceability.
