### ISSUE TITLE
AVASS1- Login as user with Id first time after registration

### ISSUE THREAD

**Issue by arunimanandy** [Scjatto/UCHSClient#3]
Login screen has a long scroll and login button overlaying the screen 

Steps to recreate :

1. User Clicks on application icon
2. User clicks login button
3. User selects User from Select Category dropdown
    User enters data
    Id = testUser
    pasword = 2@abc

![Login Screen](https://user-images.githubusercontent.com/49411568/83938899-2b642c00-a7f6-11ea-8b4e-e9a2be5aab23.jpg)

**Comment by Scjatto** [comment]
This was a problem with the layout that was being used in the login screen UI... The ScrollView was behaving in strange ways. So it was changed to a ConstraintLayout in later releases.

**Comment by Scjatto** [comment]
The bug has been fixed now. The UI would be taken up for enhancing later

**Comment by arunimanandy** [comment]
issue fixed within release 0.2
