### ISSUE TITLE
AVASS104 - Skip Configure SOP option

### ISSUE THREAD

**Issue by arunimanandy** [Scjatto/UCHSClient#4]
System Crashed on clicking Skip button in configure SOP

Steps to recreate:
1. User logged in after registration without configuring SOP
2. User clicks Skip

**Comment by Scjatto** [comment]
There was a problem with the data  `intent` from `ConfigureSOP` to `RaiseAlarm`.
This issue is fixed and checked in

**Comment by arunimanandy** [comment]
issue fixed in release 0.3
