### ISSUE TITLE
AVASS62,2,83,86 - Login as user with Phone no for subsequent time(s) after configuring SOP

### ISSUE THREAD

**Issue by arunimanandy** [Scjatto/UCHSClient#5]
User cannot log in with phone number.

Steps to recreate:
1. User clicks on application icon
2. User clicks Login 
3. User selects User from Select Category dropdown
    User enters data
    phone number = 9874563210
    password = 2@abc
4. User clicks on login button

**Comment by Scjatto** [comment]
Since the phone number logic is not implemented, this will be taken up later

**Comment by arunimanandy** [comment]
issue will be taken up later UI changed accordingly
