### ISSUE TITLE
AVASS141,138,142,137,139,140,143,144,136 - New user registers with userID as blank space

### ISSUE THREAD

**Issue by arunimanandy** [Scjatto/UCHSClient#6]
Blank space accepted as UserId

Steps to recreate:
1. Click on App icon
2. User Clicks on Register Button
3. User selects Category
    Category = User
4. Enter Data
    name = cjn
    phone no = 9874563210
    profession = Fire
    Age = 30
    Username =   
    password = 2@abc

**Comment by Scjatto** [comment]
This bug has arisen due to the improper handling of the registration form fields. The button listener `registerSubmitListener` has been modified to check for the spaces in UserID or Username.

**Comment by arunimanandy** [comment]
issue fixed in release 0.3
