### ISSUE TITLE
AVASS78,44 - New user registers with name having special charachters

### ISSUE THREAD

**Issue by arunimanandy** [Scjatto/UCHSClient#7]
Name with special characters accepted 

Steps to recreate:
1. Click on App icon
2. User Clicks on Register Button
3. User selects Category
    Category = Helpline
4. Enter Data
    name = test!er
    phone no = 9874563210
    Service Type= Fire
    Username = testUser
    password = 2@abc

**Comment by Scjatto** [comment]
This can be considered as a feature, giving liberty to the users to have special characters in their names.

**Comment by arunimanandy** [comment]
issue closed
