### ISSUE TITLE
AVASS156,80,81 - Return to Starting page from register page after registration failure

### ISSUE THREAD

**Issue by arunimanandy** [Scjatto/UCHSClient#8]
Raise alarm screen for logged out user opens after exiting from unsuccessful registration

Steps to recreate: 
1. Click App icon
2. Click Login
3. Choose category User
    Enter data:
    ID = testUser
    password = 2@abc
4. Click on menu icon
5. Click Logout
6. Click Yes
7. Click Register
8. Enter following details
    name = tester 2
    phone no = 9874563211
    profession = Fire
    Age = 30
    Username = testUser
    password = test@1234
9. Click Back button

**Comment by arunimanandy** [comment]
comment on the issue @Scjatto

**Comment by Scjatto** [comment]
The issue was basically on the residual activity stack of the application during the `logout`, and also an unhandled intent in the RegisterActivity. This issue has been fixed by assigning an intent by overriding the `onBackPressed` method.

**Comment by arunimanandy** [comment]
issue fixed in release 0.3
