### ISSUE TITLE
AVASS50,51,72,73 - New user registers with password more than 15 characters

### ISSUE THREAD

**Issue by arunimanandy** [Scjatto/UCHSClient#9]
Passwords with more than 15 characters accepted.
Steps to recreate:
1. Click on App icon
2. User Clicks on Register Button
3. User selects Category
    Category = User
4. Enter Data
    name = new user
    phone no = 9874563210
    profession = Fire
    Age = 30
    Username = testUser
    password = 2@abc5878qazwsx-7
5. Click Register button

**Comment by Scjatto** [comment]
No such constraint has been implemented on the password field. We might use the constraint in the future

**Comment by abhirup-dev** [comment]
This constraint of 15 seems unnecessary. However, it is important to document the character upper limit of the password field in our database.

**Comment by arunimanandy** [comment]
issue closed
